export const equipmentStats = new Map([
    [111, {name : "PA", density: 100, negative: false}],
    [112, {name: "Dommages", density: 20, negative: false}],
    [113, {name: "", density: 0, negative: false}],
    [114, {name: "", density: 0, negative: false}],
    [115, {name: "% Critique", density: 10, negative: false}],
    [116, {name: "Portée", density: 51, negative: true}],
    [117, {name: "Portée", density: 51, negative: false}],
    [118, {name: "Force", density: 1, negative: false}],
    [119, {name: "Agilité", density: 1, negative: false}],
    [120, {name: "", density: 0, negative: false}],
    [121, {name: "", density: 0, negative: false}],
    [122, {name: "", density: 0, negative: false}],
    [123, {name: "Chance", density: 1, negative: false}],
    [124, {name: "Sagesse", density: 1/3, negative: false}],
    [125, {name: "Vitalité", density: 1/5, negative: false}],
    [126, {name: "Intelligence", density: 1, negative: false}],
    [127, {name: "", density: 0, negative: false}],
    [128, {name: "PM", density: 90, negative: false}],
    [129, {name: "", density: 0, negative: false}],
    [130, {name: "", density: 0, negative: false}],
    [131, {name: "", density: 0, negative: false}],
    [132, {name: "", density: 0, negative: false}],
    [133, {name: "", density: 0, negative: false}],
    [134, {name: "", density: 0, negative: false}],
    [135, {name: "", density: 0, negative: false}],
    [136, {name: "", density: 0, negative: false}],
    [137, {name: "", density: 0, negative: false}],
    [138, {name: "Puissance", density: 2, negative: false}],
    [139, {name: "", density: 0, negative: false}],
    [140, {name: "", density: 0, negative: false}],
    [141, {name: "", density: 0, negative: false}],
    [142, {name: "", density: 0, negative: false}],
    [143, {name: "", density: 0, negative: false}],
    [144, {name: "", density: 0, negative: false}],
    [145, {name: "", density: 0, negative: false}],
    [146, {name: "", density: 0, negative: false}],
    [147, {name: "", density: 0, negative: false}],
    [148, {name: "", density: 0, negative: false}],
    [149, {name: "", density: 0, negative: false}],
    [150, {name: "", density: 0, negative: false}],
    [151, {name: "", density: 0, negative: false}],
    [152, {name: "Chance", density: 1, negative: true}],
    [153, {name: "", density: 0, negative: false}],
    [154, {name: "Agilité", density: 1, negative: true}],
    [155, {name: "Intelligence", density: 1, negative: true}],
    [156, {name: "", density: 0, negative: false}],
    [157, {name: "Force", density: 1, negative: true}], 
    [158, {name: "Pods", density: 1/10, negative: false}],
    [159, {name: "", density: 0, negative: false}],
    [160, {name: "Esquive PA", density: 7, negative: false}],
    [161, {name: "Esquive PM", density: 7, negative: false}],
    [171, {name: "% Critique", density: 10, negative: true}],
    [176, {name: "Prospection", density: 3, negative: false}],
    [174, {name: "Initiative", density: 0.1, negative: false}],
    [178, {name: "Soins", density: 10, negative: false}],
    [182, {name: "Invocations", density: 30, negative: false}],
    [210, {name: "% Résistance Terre", density: 6, negative: false}],
    [211, {name: "% Résistance Eau", density: 6, negative: false}],
    [212, {name: "% Résistance Air", density: 6, negative: false}],
    [213, {name: "% Résistance Feu", density: 6, negative: false}],
    [214, {name: "% Résistance Neutre", density: 6, negative: false}],
    [225, {name: "Dommages Pièges", density: 5, negative: false}],
    [240, {name: "Résistance Terre", density: 2, negative: false}],
    [241, {name: "Résistance Eau", density: 2, negative: false}],
    [242, {name: "Résistance Air", density: 2, negative: false}],
    [243, {name: "Résistance Feu", density: 2, negative: false}],
    [244, {name: "Résistance Neutre", density: 2, negative: false}],
    [411, {name: "Retrait PA", density: 7, negative: false}],
    [411, {name: "Retrait PA", density: 7, negative: true}],
    [412, {name: "Retrait PM", density: 7, negative: false}],
    [413, {name: "Retrait PM", density: 7, negative: true}],
    [414, {name: "Dommages poussée", density: 5, negative: false}],
    [416, {name: "Résistance poussée", density: 2, negative: false}],
    [417, {name: "Résistance poussée", density: 2, negative: true}],
    [418, {name: "Dommages Critiques", density: 4, negative: false}],
    [419, {name: "Dommages Critiques", density: 4, negative: true}],
    [420, {name: "Résistance Critique", density: 2, negative: false}],
    [422, {name: "Dommages Terre", density: 5, negative: false}],
    [423, {name: "Dommages Terre", density: 5, negative: true}],
    [424, {name: "Dommages Feu", density: 5, negative: false}],
    [425, {name: "Dommages Feu", density: 5, negative: true}],
    [426, {name: "Dommages Eau", density: 5, negative: false}],
    [427, {name: "Dommages Eau", density: 5, negative: true}],
    [428, {name: "Dommages Air", density: 5, negative: false}],
    [429, {name: "Dommages Air", density: 5, negative: true}],
    [430, {name: "Dommages Neutre", density: 5, negative: false}],
    [431, {name: "Dommages Neutre", density: 5, negative: true}],
    [752, {name: "Fuite", density: 4, negative: false}],
    [753, {name: "Tacle", density: 4, negative: false}],
    [754, {name: "Fuite", density: 4, negative: true}],
    [755, {name: "Tacle", density: 4, negative: true}],
    [985, {name: "Modifié par", density: 0, negative: false, reverse: true}],
    [988, {name: "Farbriqué par", density: 0, negative: false, reverse: true}],
    [2800, {name: "% Dommages mêlée", density: 15, negative: false}],
    [2801, {name: "% Dommages mêlée", density: 15, negative: true}],
    [2802, {name: "% Résistance mêlée", density: 15, negative: true}],
    [2804, {name: "% Dommages distance", density: 15, negative: false}],
    [2806, {name: "% Résistance distance", density: 15, negative: true}],
    [2807, {name: "% Résistance distance", density: 15, negative: false}],
    [2812, {name: "% Dommages aux sorts", density: 15, negative: false}],
    [2825, {name: "Empêche les futures forgemagies", density: 0, negative: false, reverse: true}],
]);

export const statImage = new Map([
    [undefined, ""],
    ["Vitalité", "/img/characteristics/tx_health.png"],
    ["PA", "/img/characteristics/tx_actionPoints.png"],
    ["Dommages", "/img/characteristics/tx_damage.png"],
    ["% Critique", "/img/characteristics/tx_crit.png"],
    ["Portée", "/img/characteristics/tx_range.png"],
    ["Force", "/img/characteristics/tx_res_earth.png"],
    ["Agilité", "/img/characteristics/tx_res_air.png"],
    ["Chance", "/img/characteristics/tx_res_water.png"],
    ["Sagesse", "/img/characteristics/tx_carac_wisdom.png"],
    ["Intelligence", "/img/characteristics/tx_res_fire.png"],
    ["PM", "/img/characteristics/tx_movementPoints.png"],
    ["Puissance", "/img/characteristics/tx_stamina.png"],
    ["Pods", "/img/characteristics/tx_pods.png"],
    ["Esquive PM", "/img/characteristics/tx_dodgeMP.png"],
    ["Prospection", "/img/characteristics/tx_prospecting.png"],
    ["Initiative", "/img/characteristics/tx_initiative.png"],
    ["Soins", "/img/characteristics/tx_heal.png"],
    ["Invocations", "/img/characteristics/tx_summonableCreaturesBoost.png"],
    ["% Résistance Terre", "/img/characteristics/tx_res_strength.png"],
    ["% Résistance Eau", "/img/characteristics/tx_res_chance.png"],
    ["% Résistance Air", "/img/characteristics/tx_res_agility.png"],
    ["% Résistance Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["% Résistance Neutre", "/img/characteristics/tx_res_neutre.png"],
    ["Dommages Pièges", "/img/characteristics/tx_trap.png"],
    ["Résistance Terre", "/img/characteristics/tx_res_strength.png"],
    ["Résistance Eau", "/img/characteristics/tx_res_chance.png"],
    ["Résistance Air", "/img/characteristics/tx_res_agility.png"],
    ["Résistance Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["Résistance Neutre", "/img/characteristics/tx_res_neutre.png"],
    ["Retrait PA", "/img/characteristics/tx_attackAP.png"],
    ["Retrait PA", "/img/characteristics/tx_dodgeAP.png"],
    ["Retrait PM", "/img/characteristics/tx_attackMP.png"],
    ["Retrait PM", "/img/characteristics/tx_dodgeMP.png"],
    ["Dommages poussée", "/img/characteristics/tx_push.png"],
    ["Résistance poussée", "/img/characteristics/tx_pushReduction.png"],
    ["Dommages Critiques", "/img/characteristics/tx_criticalDamage.png"],
    ["Résistance Critique", "/img/characteristics/tx_criticalReduction.png"],
    ["Dommages Terre", "/img/characteristics/tx_res_earth.png"],
    ["Dommages Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["Dommages Eau", "/img/characteristics/tx_res_water.png"],
    ["Dommages Air", "/img/characteristics/tx_res_air.png"],
    ["Dommages Neutre", "/img/characteristics/tx_res_neutral.png"],
    ["Fuite", "/img/characteristics/tx_escape.png"],
    ["Tacle", "/img/characteristics/tx_tackle.png"],
    ["Fuite", "/img/characteristics/tx_escape.png"],
    ["Tacle", "/img/characteristics/tx_tackle.png"],
    ["% Dommages mêlée", "/img/characteristics/tx_meleeDamage.png"],
    ["% Résistance mêlée", "/img/characteristics/tx_res_melee.png"],
    ["% Dommages distance", "/img/characteristics/tx_distanceDamage.png"],
    ["% Résistance distance", "/img/characteristics/tx_res_distance.png"],
    ["% Dommages aux sorts", "/img/characteristics/tx_weaponDamage.png"]
])