export const equipmentStats = new Map([
    [111, {name : "PA", negative: false}],
    [112, {name: "Dommages", negative: false}],
    [113, {name: "", negative: false}],
    [114, {name: "", negative: false}],
    [115, {name: "% Critique", negative: false}],
    [116, {name: "Portée", negative: true}],
    [117, {name: "Portée", negative: false}],
    [118, {name: "Force", negative: false}],
    [119, {name: "Agilité", negative: false}],
    [120, {name: "", negative: false}],
    [121, {name: "", negative: false}],
    [122, {name: "", negative: false}],
    [123, {name: "Chance", negative: false}],
    [124, {name: "Sagesse", negative: false}],
    [125, {name: "Vitalité", negative: false}],
    [126, {name: "Intelligence", negative: false}],
    [127, {name: "", negative: false}],
    [128, {name: "PM", negative: false}],
    [129, {name: "", negative: false}],
    [130, {name: "", negative: false}],
    [131, {name: "", negative: false}],
    [132, {name: "", negative: false}],
    [133, {name: "", negative: false}],
    [134, {name: "", negative: false}],
    [135, {name: "", negative: false}],
    [136, {name: "", negative: false}],
    [137, {name: "", negative: false}],
    [138, {name: "Puissance", negative: false}],
    [139, {name: "", negative: false}],
    [140, {name: "", negative: false}],
    [141, {name: "", negative: false}],
    [142, {name: "", negative: false}],
    [143, {name: "", negative: false}],
    [144, {name: "", negative: false}],
    [145, {name: "", negative: false}],
    [146, {name: "", negative: false}],
    [147, {name: "", negative: false}],
    [148, {name: "", negative: false}],
    [149, {name: "", negative: false}],
    [150, {name: "", negative: false}],
    [151, {name: "", negative: false}],
    [152, {name: "Chance", negative: true}],
    [153, {name: "", negative: false}],
    [154, {name: "Agilité", negative: true}],
    [155, {name: "Intelligence", negative: true}],
    [156, {name: "", negative: false}],
    [157, {name: "Force", negative: true}], 
    [158, {name: "Pods", negative: false}],
    [159, {name: "", negative: false}],
    [160, {name: "", negative: false}],
    [161, {name: "Esquive PM", negative: false}],
    [171, {name: "% Critique", negative: true}],
    [176, {name: "Prospection", negative: false}],
    [174, {name: "Initiative", negative: false}],
    [178, {name: "Soins", negative: false}],
    [182, {name: "Invocations", negative: false}],
    [210, {name: "% Résistance Terre", negative: false}],
    [211, {name: "% Résistance Eau", negative: false}],
    [212, {name: "% Résistance Air", negative: false}],
    [213, {name: "% Résistance Feu", negative: false}],
    [214, {name: "% Résistance Neutre", negative: false}],
    [240, {name: "Résistance Terre", negative: false}],
    [411, {name: "Retrait PA", negative: false}],
    [411, {name: "Retrait PA", negative: true}],
    [412, {name: "Retrait PM", negative: false}],
    [412, {name: "Retrait PM", negative: true}],
    [414, {name: "Dommages poussée", negative: false}],
    [416, {name: "Résistance poussée", negative: false}],
    [418, {name: "Dommages Critiques", negative: false}],
    [420, {name: "Résistance Critique", negative: false}],
    [422, {name: "Dommages Terre", negative: false}],
    [423, {name: "Dommages Terre", negative: true}],
    [424, {name: "Dommages Feu", negative: false}],
    [425, {name: "Dommages Feu", negative: true}],
    [426, {name: "Dommages Eau", negative: false}],
    [427, {name: "Dommages Eau", negative: true}],
    [428, {name: "Dommages Air", negative: false}],
    [429, {name: "Dommages Air", negative: true}],
    [430, {name: "Dommages Neutre", negative: false}],
    [431, {name: "Dommages Neutre", negative: true}],
    [752, {name: "Fuite", negative: false}],
    [753, {name: "Tacle", negative: false}],
    [754, {name: "Fuite", negative: true}],
    [755, {name: "Tacle", negative: true}],
    [985, {name: "Modifié par", negative: false, reverse: true}],
    [988, {name: "Farbriqué par", negative: false, reverse: true}],
    [2800, {name: "% Dommages mêlée", negative: false}],
    [2801, {name: "% Dommages mêlée", negative: true}],
    [2802, {name: "% Résistance mêlée", negative: true}],
    [2804, {name: "% Dommages distance", negative: false}],
    [2806, {name: "% Résistance distance", negative: true}],
    [2807, {name: "% Résistance distance", negative: false}],
    [2812, {name: "% Dommages aux sorts", negative: false}],
    [2825, {name: "Empêche les futures forgemagies", negative: false, reverse: true}],
]);

export const statImage = new Map([
    [undefined, ""],
    ["Vitalité", "/img/characteristics/tx_health.png"],
    ["PA", "/img/characteristics/tx_actionPoints.png"],
    ["Dommages", "/img/characteristics/tx_damage.png"],
    ["% Critique", "/img/characteristics/tx_crit.png"],
    ["Portée", "/img/characteristics/tx_range.png"],
    ["Force", "/img/characteristics/tx_res_earth.png"],
    ["Agilité", "/img/characteristics/tx_res_air.png"],
    ["Chance", "/img/characteristics/tx_res_water.png"],
    ["Sagesse", "/img/characteristics/tx_carac_wisdom.png"],
    ["Intelligence", "/img/characteristics/tx_res_fire.png"],
    ["PM", "/img/characteristics/tx_movementPoints.png"],
    ["Puissance", "/img/characteristics/tx_stamina.png"],
    ["Pods", "/img/characteristics/tx_pods.png"],
    ["Esquive PM", "/img/characteristics/tx_dodgeMP.png"],
    ["Prospection", "/img/characteristics/tx_prospecting.png"],
    ["Initiative", "/img/characteristics/tx_initiative.png"],
    ["Soins", "/img/characteristics/tx_heal.png"],
    ["Invocations", "/img/characteristics/tx_summonableCreaturesBoost.png"],
    ["% Résistance Terre", "/img/characteristics/tx_res_strength.png"],
    ["% Résistance Eau", "/img/characteristics/tx_res_chance.png"],
    ["% Résistance Air", "/img/characteristics/tx_res_agility.png"],
    ["% Résistance Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["% Résistance Neutre", "/img/characteristics/tx_res_neutre.png"],
    ["Résistance Terre", "/img/characteristics/tx_res_strength.png"],
    ["Résistance Eau", "/img/characteristics/tx_res_chance.png"],
    ["Résistance Air", "/img/characteristics/tx_res_agility.png"],
    ["Résistance Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["Résistance Neutre", "/img/characteristics/tx_res_neutre.png"],
    ["Retrait PA", "/img/characteristics/tx_attackAP.png"],
    ["Retrait PA", "/img/characteristics/tx_dodgeAP.png"],
    ["Retrait PM", "/img/characteristics/tx_attackMP.png"],
    ["Retrait PM", "/img/characteristics/tx_dodgeMP.png"],
    ["Dommages poussée", "/img/characteristics/tx_push.png"],
    ["Résistance poussée", "/img/characteristics/tx_pushReduction.png"],
    ["Dommages Critiques", "/img/characteristics/tx_criticalDamage.png"],
    ["Résistance Critique", "/img/characteristics/tx_criticalReduction.png"],
    ["Dommages Terre", "/img/characteristics/tx_res_earth.png"],
    ["Dommages Feu", "/img/characteristics/tx_res_intelligence.png"],
    ["Dommages Eau", "/img/characteristics/tx_res_water.png"],
    ["Dommages Air", "/img/characteristics/tx_res_air.png"],
    ["Dommages Neutre", "/img/characteristics/tx_res_neutral.png"],
    ["Fuite", "/img/characteristics/tx_escape.png"],
    ["Tacle", "/img/characteristics/tx_tackle.png"],
    ["Fuite", "/img/characteristics/tx_escape.png"],
    ["Tacle", "/img/characteristics/tx_tackle.png"],
    ["% Dommages mêlée", "/img/characteristics/tx_meleeDamage.png"],
    ["% Résistance mêlée", "/img/characteristics/tx_res_melee.png"],
    ["% Dommages distance", "/img/characteristics/tx_distanceDamage.png"],
    ["% Résistance distance", "/img/characteristics/tx_res_distance.png"],
    ["% Dommages aux sorts", "/img/characteristics/tx_weaponDamage.png"]
])